//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.MsSql.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repository.MsSql.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;NextDataLayer&apos;)
        ///	BEGIN
        ///		CREATE DATABASE [NextDataLayer]
        ///	END
        ///
        ///.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [NextDataLayer]
        ///
        ///IF NOT EXISTS (SELECT * FROM sysobjects WHERE name=&apos;Products&apos; AND xtype=&apos;U&apos;)
        ///	BEGIN
        ///
        ///		CREATE TABLE Products (
        ///			[Id] int IDENTITY(1,1) NOT NULL,
        ///			[Name] nvarchar(180) NULL,
        ///			[Description] nvarchar(250) NULL,
        ///			CONSTRAINT [PK_Products_ID] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///	) ON [PRIMARY] 
        ///		
        ///	END
        ///
        ///IF NOT EXISTS (SELECT * FROM sysobjects  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [NextDataLayer]
        ///
        ///IF  NOT EXISTS (SELECT * from products )
        ///	BEGIN
        ///
        ///	INSERT INTO Products ([Name],[Description]) values
        ///		(&apos;Galaxy S6&apos;,&apos;3GB RAM 32 Internal Storage&apos;), 
        ///		(&apos;Lenovo L430&apos;,&apos;Pentium I5 960GB SSD&apos;),
        ///		(&apos;Logitech Headset&apos;,&apos;wireless, USB recharege&apos;)
        ///
        ///	END
        ///
        ///.
        /// </summary>
        internal static string SeedDatabase {
            get {
                return ResourceManager.GetString("SeedDatabase", resourceCulture);
            }
        }
    }
}
